---
# Source: btp-service-operator/charts/sap-btp-services/templates/services-binding-services-cloud-sap.yaml
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: hana-binding
  namespace: default
  labels:
    openmcp.cloud/blueprint-building-block: "sap-btp-services"
    openmcp.cloud/blueprint-building-block-version: "0.0.12"
spec:
  serviceInstanceName: hana-cloud
  secretName: hana-binding-secret
  parameters:
    []
  credentialsRotationPolicy:
    enabled: false
    rotatedBindingTTL: 1s
    rotationFrequency: 1s
