---
# Source: btp-service-operator/charts/crossplane-provider-sap-btp-account/templates/mcp/btp-accounts/sub-accounts.yaml
apiVersion: account.btp.sap.crossplane.io/v1alpha1
kind: Subaccount
metadata:
  name: subaccount1
  labels:
    openmcp.cloud/blueprint-building-block: "crossplane-provider-sap-btp-account"
    openmcp.cloud/blueprint-building-block-version: "0.0.6"
spec:
  forProvider:
    description: Cloud Orchestrator Managed Control Plane Blueprint PoC
    displayName: ""
    region: eu30
    subaccountAdminEmails: []
    subdomain: ""
  providerConfigRef:
    name: ""
