# pipeline feature flags obsolete (Bash Scripts)
jfrog.sh:
  enabled: true

# pipeline feature flags
helm-docs:
  enable: true
helm-chart-linting:
  enable: true
helm-chart-validation:
  enable: true
helm-chart-version-bump:
  enable: true
helm-chart-dependency-update:
  enable: true
k8s-manifest-templating:
  enable: true
  helm-charts: 
    default-manifest-templating: true # disables stanard helm mainfest templating
    additional-manifest-templating: # define this if you want additional helm manifest folder e.g. dev....
    - prefix-manifest-folder-name: "dev"
      value-files:
        - "values.yaml"
        - "values.network.yaml"
        - "values.dev.yaml"
