---
######################################################################################################################################
tags: # see ./Chart.yaml @url: https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies
  external-secrets-config: true
  crossplane-provider-configs: true
  crossplane-provider-sap-btp-account: true
  crossplane-provider-sap-btp-environment: true
######################################################################################################################################
external-secrets-config:
  secretStores:
  - name: "hashicorp-vault"
    namespace: "default"
    provider:
      vault:
        auth:
          kubernetes:
            secretRef:
              name: "ASDA-tokenreview-service-account"
  externalSecret:
    - name: "ASDA-btp-account-mcp-blueprints"
      namespace: "ASDA-default"
      refreshInterval: "30m"
      targetSecretName: "ASDA-btp-account-credentials"
      secretStore:
        name: "hashicorp-vault"
