---
######################################################################################################################################
tags: # see ./Chart.yaml @url: https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies
  external-secrets-config: true
  crossplane-provider-configs: true
  crossplane-provider-sap-btp-account: true
  crossplane-provider-sap-btp-environment: true
######################################################################################################################################
external-secrets-config:
  secretStores:
  - name: "hashicorp-vault"
    namespace: "default"
    provider:
      vault:
        server: "https://vault.example/"
        namespace: "openmcp/blueprints"
        path: "mcps"
        version: "v2"
        auth:
          kubernetes:
            mountPath: "k8s-openmcp-blueprints"
            role: "k8s-openmcp-role"
            secretRef:
              name: "vault-tokenreview-service-account"
              namespace: "default"
              key: "token"
  externalSecret:
    - name: "btp-account-mcp-blueprints"
      namespace: "default"
      refreshInterval: "15m"
      targetSecretName: "btp-account-credentials"
      secretStore:
        name: "hashicorp-vault"
      data:
        - secretKey: btp-cis-provider-credentials
          remoteRef:
            key: "btp-endpoint.example/btp-account"
            property: btp-cis-provider-credentials
        - secretKey: btp-service-account-provider-credentials
          remoteRef:
            key: "btp-endpoint.example/btp-account"
            property: btp-service-account-provider-credentials
######################################################################################################################################
crossplane-provider-configs:
  providerConfigs:
    btpSapCrossplane:
      - providerConfigRefName: "btp-account-provider-config"
        globalAccountSubDomain: "exmpl"
        cliServerUrl: "https://cli.btp.cloud.sap"
        cisCredentials:
          source: "Secret"
          secretRef:
            namespace: default
            name: "btp-account-mcp-blueprints"
            key: btp-cis-provider-credentials
        serviceAccountSecret:
          source: "Secret"
          secretRef:
            namespace: default
            name: "btp-account-mcp-blueprints"
            key: btp-service-account-provider-credentials
#########################################################################################################
crossplane-provider-sap-btp-account:
  cfAdminEmails: &cfAdminEmails []
  subaccountAdmins: &subaccountAdmins []
  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#        
  btpEntitlements: &btpEntitlements    
  - name: "kymaruntime-gcp"
    serviceName: "kymaruntime"
    servicePlanName: "gcp"
    permitNumericQuota: true
    amount: 1
  - name: "cis-local"
    serviceName: cis
    servicePlanName: local
    permitNumericQuota: false
    amount: 1
  #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#        
  accounts:
    - btpSapCrossplaneProviderConfigRefName: "btp-account-provider-config"
      #-------------------------------------------------------------------------------------------------------------------------#
      #++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
      subAccounts:
        #-------------------------------------------------------------------------------------------------------------------------#
        - name: "subAccount1"
          forProvider:
            displayName: "exmpl dev eu01"
            description: "Open Orchestrator Managed Control Plane Blueprint PoC"
            subdomain: "exmpl-dev-eu01"
            region: "eu01"
            subaccountAdmins: *subaccountAdmins
          entitlements: *btpEntitlements
          services:
            serviceManager: true
            cloudManagement: true
        #-------------------------------------------------------------------------------------------------------------------------#                                     
#########################################################################################################
crossplane-provider-sap-btp-environment:
  kymaEnvironments:
  - btpSapCrossplaneProviderConfigRefName: "btp-account-provider-config"
    name: "kyma-test"
    forProvider:
      parameters:
        administrators: *subaccountAdmins
        autoScalerMax: 9
        autoScalerMin: 6
        machineType: "n2-standard-48" 
        region: "europe-west3"
      planName: "gcp"
    cloudManagementRef:
      name: "dev-eu01"
    subaccountRef:
      name: "dev-eu01"
    writeConnectionSecretToRef:
      name: "kyma-kubeconfig-local"
      namespace: "default"
#########################################################################################################