---
apiVersion: v2
name: provider-gardener-existing
description: A Umbrealla Helm chart which contains crossplane manifests to demonstrate orchestration of (already) existing SAP Gardener Clusters and its stack
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into
# versioned archives to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer.
# They're included as a dependency of application charts to inject those
# utilities and functions into the rendering pipeline. Library charts
# do not define any templates and therefore cannot be deployed.
type: application
# A URL to an SVG or PNG image to be used as an icon
icon: "https://avatars.githubusercontent.com/u/2531208?s=200&v=4"
# This is the chart version. This version number should be incremented each time
# you make changes to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

version: 0.0.20

# This is the version number of the application being deployed. This version
# number should be incremented each time you make changes to the application.
# Versions are not expected to follow Semantic Versioning. They should reflect
# the version the application is using. It is recommended to use it with quotes.
appVersion: "0.0.1"
dependencies:
  - name: crossplane-provider-configs
    alias: crossplane-provider-configs
    version: 0.0.15
    repository: " https://raw.githubusercontent.com/openmcp-project/blueprint-building-blocks/gh-pages/"
    tags:
      - crossplane-provider-configs
  - name: external-secrets-config
    alias: external-secrets-config
    version: 0.1.7
    repository: " https://raw.githubusercontent.com/openmcp-project/blueprint-building-blocks/gh-pages/"
    tags:
      - external-secrets-config
  - name: crossplane-gardener-shoot-kubeconfigs
    alias: crossplane-gardener-shoot-kubeconfigs
    version: 0.0.7
    repository: " https://raw.githubusercontent.com/openmcp-project/blueprint-building-blocks/gh-pages/"
    tags:
      - crossplane-gardener-shoot-kubeconfigs
  - name: crossplane-provider-helm
    alias: crossplane-provider-helm
    version: 0.0.8
    repository: " https://raw.githubusercontent.com/openmcp-project/blueprint-building-blocks/gh-pages/"
    tags:
      - crossplane-provider-helm
