---
# Source: provider-gardener-existing/charts/external-secrets-config/templates/secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "hashicorp-vault"
  namespace: "default"
  labels:
    openmcp.cloud/blueprint-building-block: "external-secrets-config"
    openmcp.cloud/blueprint-building-block-version: "0.1.7"
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: 
          role: 
          secretRef:
            key: token
            name: 
            namespace: default
      namespace: ts-co-openmcp/mcp-blueprints
      path: mcps
      server: 
      version: v2
