---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-iam/templates/role-policy-attachment-iam-aws-upbound-io.yaml
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: dev-ekscluster
  annotations:
    crossplane.io/composition-resource-name: rolePolicyAttachment
  labels:
    openmcp.cloud/blueprint-building-block: "crossplane-provider-aws-iam"
    openmcp.cloud/blueprint-building-block-version: "0.0.14"
    crossplane.io/claim-namespace: dev-us
    crossplane.io/composite: dev-ekscluster
  ownerReferences:
    - apiVersion: api.example/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: EKSCluster
      name: dev-ekscluster
      uid: ""
spec:
  deletionPolicy: ""
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    roleSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
