---
# Source: migration-test-provider-btp-accounts/charts/crossplane-provider-sap-btp-account/templates/mcp/btp-accounts/sub-accounts.yaml
apiVersion: account.btp.sap.crossplane.io/v1alpha1
kind: Subaccount
metadata:
  name: subaccount1
  labels:
    openmcp.cloud/blueprint-building-block: "crossplane-provider-sap-btp-account"
    openmcp.cloud/blueprint-building-block-version: "0.0.2"
spec:
  forProvider:
    description: 'Sub Account managed by MCP & IaD from MCP #2'
    displayName: 'MCP #1 Blueprint Sub-Account #1'
    region: ""
    subaccountAdmins:
    - steffen.kelch@sap.com
    - DL_66C5ED1CCC389201361635EC@global.corp.sap
    subdomain: blueprint-test-1
  providerConfigRef:
    name: "btp-account-mcp-blueprints"
---
# Source: migration-test-provider-btp-accounts/charts/crossplane-provider-sap-btp-account/templates/mcp/btp-accounts/sub-accounts.yaml
apiVersion: account.btp.sap.crossplane.io/v1alpha1
kind: Subaccount
metadata:
  name: subaccount2
  labels:
    openmcp.cloud/blueprint-building-block: "crossplane-provider-sap-btp-account"
    openmcp.cloud/blueprint-building-block-version: "0.0.2"
spec:
  forProvider:
    description: 'Sub Account managed by MCP & IaD from MCP #2 new'
    displayName: 'MCP #1 Blueprint Sub-Account #2'
    region: ""
    subaccountAdmins:
    - steffen.kelch@sap.com
    - DL_66C5ED1CCC389201361635EC@global.corp.sap
    subdomain: blueprint-test-2
  providerConfigRef:
    name: "btp-account-mcp-blueprints"
