---
# Source: btp-kyma-env-runtime/charts/crossplane-provider-sap-btp-environment/templates/kyma-environment.yaml
apiVersion: environment.btp.sap.crossplane.io/v1alpha1
kind: KymaEnvironment
metadata:
  name: provider-config-""-kyma-test
  labels:
    openmcp.cloud/blueprint-building-block: "crossplane-provider-sap-btp-environment"
    openmcp.cloud/blueprint-building-block-version: "0.0.12"
spec:
  providerConfigRef:
    name: provider-config-""
  forProvider:
    parameters:
      administrators:
      - steffen.brunner@sap.com
      - dl_66c9ed85dbece8d67bc369c4@global.corp.sap
      autoScalerMax: 9
      autoScalerMin: 6
      machineType: n2-standard-48
      region: europe-west3
    planName: gcp
  cloudManagementRef:
    name: ""
  subaccountRef:
    name: ""
  writeConnectionSecretToRef:
    name: kyma-kubeconfig-local
    namespace: default
