---
apiVersion: v2
name: k8s-validating-admission-policy
description: A Umbrealla Helm chart which contains k8s ValidatingAdmissionPolicy & ValidatingAdmissionPolicyBinding for a couple of crossplane ProviderConfig. As of Nov 2024, mcp admins do not have permission to manage kind ValidatingAdmissionPolicy, therefore this solution can only be applied to self hosted crossplane k8s clusters!
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into
# versioned archives to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer.
# They're included as a dependency of application charts to inject those
# utilities and functions into the rendering pipeline. Library charts
# do not define any templates and therefore cannot be deployed.
type: application
# A URL to an SVG or PNG image to be used as an icon
icon: "https://avatars.githubusercontent.com/u/2531208?s=200&v=4"
# This is the chart version. This version number should be incremented each time
# you make changes to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.3
# This is the version number of the application being deployed. This version
# number should be incremented each time you make changes to the application.
# Versions are not expected to follow Semantic Versioning. They should reflect
# the version the application is using. It is recommended to use it with quotes.
appVersion: "0.0.1"
dependencies:
  - name: k8s-validating-admission-policy
    alias: k8s-validating-admission-policy
    version: 0.0.5
    repository: "oci://ghcr.io/openmcp-project"
    tags:
      - k8s-validating-admission-policy
