---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/eip-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: dev-ekscluster
spec:
  deletionPolicy: ""  
  forProvider:
    domain: vpc
    region: west-2
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/eip-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: dev-ekscluster-2
spec:
  deletionPolicy: ""  
  forProvider:
    domain: vpc
    region: west-2
  providerConfigRef:
    name: dev-aws
