---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/internet-gateway-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: dev-ekscluster
spec:
  deletionPolicy: ""  
  forProvider:
    region: west-2
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/internet-gateway-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: reference-eks-network
spec:
  deletionPolicy: ""  
  forProvider:
    region: east-1
    tags:
      Name: platform-ref-eks-network-internet-gateway
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
