---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/main-route-rable-association-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: MainRouteTableAssociation
metadata:
  name: reference-eks-network
spec:
  deletionPolicy: ""  
  forProvider:
    region: east-1
    routeTableIdSelector:
      matchControllerRef: true
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
