---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/nat-gateway-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: dev-us-ekscluster
spec:
  deletionPolicy: ""  
  forProvider:
    allocationIdSelector:
      matchLabels:
        type: eip-1
    region: us-west-2
    subnetIdSelector:
      matchLabels:
        type: subnet
        visibility: public
        zone: us-west-2a
  providerConfigRef:
    name: dev-us-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/nat-gateway-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: dev-us-ekscluster-2
spec:
  deletionPolicy: ""  
  forProvider:
    allocationIdSelector:
      matchLabels:
        type: eip-2
    region: us-west-2
    subnetIdSelector:
      matchLabels:
        type: subnet
        visibility: public
        zone: us-west-2b
  providerConfigRef:
    name: dev-us-aws
