---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/route-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: reference-eks-network
spec:
  deletionPolicy: ""  
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdSelector:
      matchControllerRef: true
    region: east-1
    routeTableIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
