---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/route-table-association-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1  
kind: RouteTableAssociation
metadata:
  name: reference-eks-network-public
spec:
  deletionPolicy: ""  
  forProvider:
    region: us-east-1
    routeTableIdSelector:
      matchControllerRef: true
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        access: public
        zone: us-east-1a
  providerConfigRef:
    name: dev-us-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/route-table-association-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1  
kind: RouteTableAssociation
metadata:
  name: reference-eks-network-private
spec:
  deletionPolicy: ""  
  forProvider:
    region: us-east-1
    routeTableIdSelector:
      matchControllerRef: true
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        access: private
        zone: us-east-1a
  providerConfigRef:
    name: dev-us-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/route-table-association-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1  
kind: RouteTableAssociation
metadata:
  name: reference-eks-network-public-1b
spec:
  deletionPolicy: ""  
  forProvider:
    region: us-east-1
    routeTableIdSelector:
      matchControllerRef: true
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        access: public
        zone: us-east-1b
  providerConfigRef:
    name: dev-us-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/route-table-association-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1  
kind: RouteTableAssociation
metadata:
  name: reference-eks-network-private-1b
spec:
  deletionPolicy: ""  
  forProvider:
    region: us-east-1
    routeTableIdSelector:
      matchControllerRef: true
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        access: private
        zone: us-east-1b
  providerConfigRef:
    name: dev-us-aws
