---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/security-group-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: reference-eks-network
spec:
  deletionPolicy: ""  
  forProvider:
    description: Allow access to databases
    name: platform-ref-eks-network-security-group
    region: us-east-1
    tags:
      Name: platform-ref-eks-network-security-group
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-us-aws
