---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/security-group-rule-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRuleRule
metadata:
  name: reference-eks-network
spec:
  deletionPolicy: ""  
  forProvider:
    cidrBlocks:
    - 192.168.0.0/16
    description: Everywhere
    fromPort: 3306
    protocol: tcp
    region: us-east-1
    securityGroupIdSelector:
      matchControllerRef: true
    toPort: 3306
    type: ingress
  providerConfigRef:
    name: dev-us-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/security-group-rule-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRuleRule
metadata:
  name: reference-eks-network-5432
spec:
  deletionPolicy: ""  
  forProvider:
    cidrBlocks:
    - 192.168.0.0/16
    description: Everywhere
    fromPort: 5432
    protocol: tcp
    region: us-east-1
    securityGroupIdSelector:
      matchControllerRef: true
    toPort: 5432
    type: ingress
  providerConfigRef:
    name: dev-us-aws
