---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/subnet-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: dev-ekscluster
spec:
  deletionPolicy: ""  
  forProvider:
    availabilityZone: west-2a
    cidrBlock: 192.168.50.0/24
    mapPublicIpOnLaunch: false
    region: west-2
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/subnet-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: reference-eks-network
spec:
  deletionPolicy: ""  
  forProvider:
    availabilityZone: east-1a
    cidrBlock: 192.168.128.0/18
    region: east-1
    tags:
      Name: platform-ref-eks-network-subnet-east-1a-private-2
      kubernetes.io/role/internal-elb: "1"
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/subnet-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: reference-eks-network-public-0
spec:
  deletionPolicy: ""  
  forProvider:
    availabilityZone: east-1a
    cidrBlock: 192.168.0.0/18
    mapPublicIpOnLaunch: true
    region: east-1
    tags:
      Name: platform-ref-eks-network-subnet-east-1a-public-0
      kubernetes.io/role/elb: "1"
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/subnet-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: reference-eks-network-east-1b-private-3
spec:
  deletionPolicy: ""  
  forProvider:
    availabilityZone: east-1b
    cidrBlock: 192.168.192.0/18
    region: east-1
    tags:
      Name: platform-ref-eks-network-subnet-east-1b-private-3
      kubernetes.io/role/internal-elb: "1"
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/subnet-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: reference-eks-network-east-1b-public-1
spec:
  deletionPolicy: ""  
  forProvider:
    availabilityZone: east-1b
    cidrBlock: 192.168.64.0/18
    mapPublicIpOnLaunch: true
    region: east-1
    tags:
      Name: platform-ref-eks-network-subnet-east-1b-public-1
      kubernetes.io/role/elb: "1"
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/subnet-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: dev-ekscluster-2
spec:
  deletionPolicy: ""  
  forProvider:
    availabilityZone: west-2b
    cidrBlock: 192.168.51.0/24
    mapPublicIpOnLaunch: false
    region: west-2
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/subnet-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: dev-ekscluster-3
spec:
  deletionPolicy: ""  
  forProvider:
    availabilityZone: west-2b
    cidrBlock: 192.168.49.0/24
    mapPublicIpOnLaunch: true
    region: west-2
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/subnet-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: dev-ekscluster-4
spec:
  deletionPolicy: ""  
  forProvider:
    availabilityZone: west-2b
    cidrBlock: 192.168.49.0/24
    mapPublicIpOnLaunch: true
    region: west-2
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: dev-aws
