---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/vpc-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: dev-ekscluster
spec:
  deletionPolicy: ""  
  forProvider:
    cidrBlock: 192.168.48.0/20
    enableDnsHostnames: true
    enableDnsSupport: true
    region: west-2
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/vpc-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: reference-eks-network
spec:
  deletionPolicy: ""  
  forProvider:
    cidrBlock: 192.168.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    region: east-1
    tags:
      Name: platform-ref-eks-network-vpc
  providerConfigRef:
    name: dev-aws
---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-ec2/templates/vpc-ec2-aws-upbound-io.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: vpc-west-2
spec:
  deletionPolicy: ""  
  forProvider:
    enableDnsHostNames: true
    enableDnsSupport: true
    instanceTenancy: default
    region: west-2
    vpcCidrBlock: 10.0.0.0/16
  providerConfigRef:
    name: dev-aws
