---
# Source: provider-aws.zzzz/charts/external-secrets-config/templates/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "btp-account-test"
  namespace: "default"
  labels:
    openmcp.cloud/blueprint-building-block: "external-secrets-config"
    openmcp.cloud/blueprint-building-block-version: "0.1.12"
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: "hashicorp-vault"    
    kind: "SecretStore"
  target:
    name: "btp-account-test"
  data:
    - remoteRef:
        key: ""
        property: btp-cis-provider-credentials
      secretKey: btp-cis-provider-credentials
    - remoteRef:
        key: ""
        property: btp-service-account-provider-credentials
      secretKey: btp-service-account-provider-credentials
