---
# Source: provider-aws.zzzz/charts/external-secrets-config/templates/secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "hashicorp-vault"
  namespace: "default"
  labels:
    openmcp.cloud/blueprint-building-block: "external-secrets-config"
    openmcp.cloud/blueprint-building-block-version: "0.1.7"
spec:
  provider:
    vault:
      auth:
        appRole:
          path: approle
          roleId: ""
          secretRef:
            key: token
            name: hashicorp-vault-token
      namespace: ""
      path: k8s-clusters
      server: 
      version: v2
