---
# Source: btp-service-operator/charts/external-secrets-config/templates/secret-store.yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: "hashicorp-vault"
  namespace: "default"
  labels:
    openmcp.cloud/blueprint-building-block: "external-secrets-config"
    openmcp.cloud/blueprint-building-block-version: "0.1.12"
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: openmcp-kubernetes
          secretRef:
            key: token
            name: vault-token-sa
            namespace: default
      namespace: ns1
      path: mcps
      server: https://vault.example/
      version: v2
