---
# Source: provider-gardener-existing/charts/crossplane-gardener-shoot-kubeconfigs/templates/mcp-manifests/admin-kubeconfig-request.yaml
apiVersion: gardener.orchestrate.cloud.sap/v1alpha1
kind: AdminKubeconfigRequest
metadata:
  name: "iad-test"
  labels:
    openmcp.cloud/blueprint-building-block: "crossplane-gardener-shoot-kubeconfigs"
    openmcp.cloud/blueprint-building-block-version: "0.0.10"
spec:
  forProvider:
    validFor: 1h0s
    renewAfter: 45m0s
    shootRef:
      name: "iad-test"
      namespace: "garden-co-golden"
  providerConfigRef:
    name: "garden-sa-co-mcp-blueprints"
  writeConnectionSecretToRef:
    name: gardener-shoot-kubeconfig-iad-test
    namespace: default
