---
# Source: provider-gardener/charts/crossplane-gardener-shoot-clusters/templates/mcp-manifests/admin-kubeconfig-request.yaml
apiVersion: gardener.orchestrate.cloud.sap/v1alpha1
kind: AdminKubeconfigRequest
metadata:
  name: "iad-test"
spec:
  forProvider:
    validFor: 1h0s
    renewAfter: 45m0s
    shootRef:
      name: "iad-test"
      namespace: "garden-co-golden"
  providerConfigRef:
    name: "garden-co-golden"
  writeConnectionSecretToRef:
    name: gardener-shoot-kubeconfig-iad-test
    namespace: default
