---
# Source: include-custom-helm-charts/charts/external-secrets-config/templates/secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "hashicorp-vault"
  namespace: "default"
  labels:
    openmcp.cloud/blueprint-building-block: "external-secrets-config"
    openmcp.cloud/blueprint-building-block-version: "0.1.7"
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: mcp-blueprints
          secretRef:
            key: token
            name: ""
            namespace: default
      namespace: "ns1"
      path: k8s-clusters
      server: vault.example
      version: v2
