---
# Source: ocm-package-provider-btp-accounts/charts/crossplane-provider-sap-btp-account/templates/mcp/btp-subscriptions/entitlements.yaml
apiVersion: account.btp.sap.crossplane.io/v1alpha1
kind: Entitlement
metadata:  
  name: auditlog-oauth2  
  labels:
    openmcp.cloud/blueprint-building-block: "crossplane-provider-sap-btp-account"
    openmcp.cloud/blueprint-building-block-version: "0.0.9"
spec:
  forProvider:    
    serviceName: auditlog-management
    servicePlanName: default
    amount: 1
    subaccountRef:
      name: subaccount1
  providerConfigRef:
    name: "provider-config-ref-name-btp-account-mcp-blueprints"
