---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-eks/templates/cluster-eks-aws-upbound-io.yaml
apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: dev-us-ekscluster
  annotations:
    crossplane.io/composition-resource-name: eks-cluster
  labels:
    openmcp.cloud/blueprint-building-block: "crossplane-provider-aws-eks"
    openmcp.cloud/blueprint-building-block-version: "0.0.12"
    crossplane.io/claim-namespace: dev-us
    crossplane.io/composite: dev-us-ekscluster
  ownerReferences:
    - apiVersion: api.example/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: XEKSCluster
      name: dev-us-ekscluster
      uid: ""
spec:
  deletionPolicy: ""
  forProvider:
    region: us-west-2
    roleArn: arn:aws:iam::XXXX:role/EKS-Cluster-Role
    version: "1.29"
    vpcConfig:
    - endpointPrivateAccess: false
      endpointPublicAccess: true
      subnetIdSelector:
        matchLabels:
          type: subnet
          visibility: private
  providerConfigRef:
    name: dev-us-aws    
  writeConnectionSecretToRef:
    name: dev-us-connection-secret
    namespace: crossplane-system
  publishConnectionDetailsTo:
    {}
