---
# Source: provider-aws.zzzz/charts/crossplane-provider-aws-eks/templates/node-group-eks-aws-upbound-io.yaml
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: dev-us-ekscluster
  annotations:
    crossplane.io/composition-resource-name: eks-nodegroup
  labels:
    openmcp.cloud/blueprint-building-block: "crossplane-provider-aws-eks"
    openmcp.cloud/blueprint-building-block-version: "0.0.12"
    crossplane.io/claim-namespace: dev-us
    crossplane.io/composite: dev-us-ekscluster
  ownerReferences:
    - apiVersion: api.example/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: XEKSCluster
      name: dev-us-ekscluster
      uid: ""
spec:
  deletionPolicy: ""
  forProvider:
    amiType: AL2_x86_64
    clusterNameSelector:
      matchControllerRef: true
    instanceTypes:
    - t3.medium
    nodeRoleArn: arn:aws:iam::XXXX:role/EKS-WorkerNode-Role
    region: us-west-2
    scalingConfig:
    - desiredSize: 2
      maxSize: 2
      minSize: 1
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        type: subnet
        visibility: private
  providerConfigRef:
    name: dev-us-aws
