name: Git PR Status Checks

on:
  pull_request: {}
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-status-check:
    uses: "openmcp-project/blueprint-workflows/.github/workflows/git-pr-status-checks.yml@main"
    secrets: inherit