name: Release Charts

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm/charts
        env:
          CR_GENERATE_RELEASE_NOTES: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser for umbrella charts
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm/umbrella/blueprints
        env:
          CR_GENERATE_RELEASE_NOTES: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upload to OCI-based registry
        run: |
          if [ -d ".cr-release-packages" ]; then
            helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            find .cr-release-packages/ -name *.tgz -exec helm push {} oci://ghcr.io/openmcp-project \;
          fi
